version: "3.8"

services:
  ####################################
  # mysql database  
  ####################################
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rooms

  ##################################
  # Pytest on Meeting Rooms Service
  ##################################
  rooms-pytest:
    build:
      context: ../
      dockerfile: ci/Dockerfile.test
    depends_on:
      - mysql
    environment:
      db_conn: mysql+mysqlconnector://root:root@mysql:3306